"""add skill_source_materials junction table

Revision ID: 089e4862b719
Revises: 960bc2f081dd
Create Date: 2026-04-11 20:39:10.289163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089e4862b719'
down_revision: Union[str, None] = '960bc2f081dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_coaching_sessions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('conference_audience_hcps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conf_audience_hcp_profile_id'))
        batch_op.drop_index(batch_op.f('ix_conf_audience_scenario_id'))
        batch_op.create_index(batch_op.f('ix_conference_audience_hcps_hcp_profile_id'), ['hcp_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_audience_hcps_scenario_id'), ['scenario_id'], unique=False)

    with op.batch_alter_table('hcp_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hcp_voice_live_instance'))
        batch_op.create_index(batch_op.f('ix_hcp_profiles_voice_live_instance_id'), ['voice_live_instance_id'], unique=False)

    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.create_index(batch_op.f('ix_session_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('voice_live_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vli_created_by'))
        batch_op.create_index(batch_op.f('ix_voice_live_instances_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_live_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_live_instances_created_by'))
        batch_op.create_index(batch_op.f('ix_vli_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_messages_session_id'))
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('hcp_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hcp_profiles_voice_live_instance_id'))
        batch_op.create_index(batch_op.f('ix_hcp_voice_live_instance'), ['voice_live_instance_id'], unique=False)

    with op.batch_alter_table('conference_audience_hcps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_audience_hcps_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_conference_audience_hcps_hcp_profile_id'))
        batch_op.create_index(batch_op.f('ix_conf_audience_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conf_audience_hcp_profile_id'), ['hcp_profile_id'], unique=False)

    with op.batch_alter_table('coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coaching_sessions_scenario_id'))
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_scenario_id'), ['scenario_id'], unique=False)

    # ### end Alembic commands ###
