"""add agent audit fields to dry_runs

Revision ID: 294a0e3dcd41
Revises: 095eed0918dc
Create Date: 2026-04-27 09:04:19.723703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294a0e3dcd41'
down_revision: Union[str, None] = '095eed0918dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dry_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mr_agent_id', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('mr_agent_version', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('hcp_agent_id', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('hcp_agent_version', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('evaluator_agent_id', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('evaluator_agent_version', sa.String(length=50), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dry_runs', schema=None) as batch_op:
        batch_op.drop_column('evaluator_agent_version')
        batch_op.drop_column('evaluator_agent_id')
        batch_op.drop_column('hcp_agent_version')
        batch_op.drop_column('hcp_agent_id')
        batch_op.drop_column('mr_agent_version')
        batch_op.drop_column('mr_agent_id')

    # ### end Alembic commands ###
