"""add meta_skills table

Revision ID: 50811ca8b0f6
Revises: df6cb9a8d3c1
Create Date: 2026-04-11 23:37:33.020793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50811ca8b0f6'
down_revision: Union[str, None] = 'df6cb9a8d3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
