"""add training material tables

Revision ID: b148c6bf1d9b
Revises: 16f9f0ba6e9d
Create Date: 2026-03-25 15:47:37.800158

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b148c6bf1d9b"
down_revision: str | None = "16f9f0ba6e9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_materials",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.Column("therapeutic_area", sa.String(length=255), nullable=False),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_materials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_materials_product"), ["product"], unique=False
        )

    op.create_table(
        "material_versions",
        sa.Column("material_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("storage_url", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["training_materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("material_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_material_versions_material_id"), ["material_id"], unique=False
        )

    op.create_table(
        "material_chunks",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("material_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("page_label", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["training_materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["material_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("material_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_material_chunks_material_id"), ["material_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_material_chunks_version_id"), ["version_id"], unique=False
        )

    with op.batch_alter_table("score_details", schema=None) as batch_op:
        batch_op.add_column(sa.Column("score", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score_details", schema=None) as batch_op:
        batch_op.drop_column("score")

    with op.batch_alter_table("material_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_material_chunks_version_id"))
        batch_op.drop_index(batch_op.f("ix_material_chunks_material_id"))

    op.drop_table("material_chunks")
    with op.batch_alter_table("material_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_material_versions_material_id"))

    op.drop_table("material_versions")
    with op.batch_alter_table("training_materials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_materials_product"))

    op.drop_table("training_materials")
    # ### end Alembic commands ###
