"""add default_project to service_configs

Revision ID: b820e86271f8
Revises: h12a00000001
Create Date: 2026-04-02 12:01:32.228818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b820e86271f8'
down_revision: Union[str, None] = 'h12a00000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_project', sa.String(length=200), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_configs', schema=None) as batch_op:
        batch_op.drop_column('default_project')

    # ### end Alembic commands ###
